### ISSUE TITLE
Throw InvalidNodeTypeError on DocumentType nodes

### ISSUE THREAD

**Issue by pshaughn** [w3c/selection-api#118]
Various methods that take a node and offset are specified as throwing IndexSizeError if the offset exceeds the node's length.
By WPT tests and by analogy with Range methods, these also need to throw InvalidNodeTypeError if the node is a DocumentType, and InvalidNodeType is the condition to check first for cases where both apply.

**Comment by rniwa** [comment]
Do all major browsers currently throw InvalidNodeTypeError?

**Comment by pshaughn** [comment]
Chrome, Firefox, and Edge do; Safari might not. https://wpt.fyi/results/selection/selectAllChildren.html?label=experimental&label=master&aligned has many cases involving a doctype.

**Comment by darinadler** [comment]
The specification already requires throwing `InvalidNodeTypeError`. Not directly, but indirectly. The specification has steps that say things like “set the start of newRange” and those steps will throw `InvalidNodeTypeError` because that’s part of the [set the start or end algorithm](https://dom.spec.whatwg.org/#concept-range-bp-set) from the DOM specification.

**Comment by darinadler** [comment]
Regarding the ordering of the checks, see also my comments in #124.

**Comment by darinadler** [comment]
Just looked at [the WPT test](https://github.com/web-platform-tests/wpt/blob/master/selection/selectAllChildren.html) and unfortunately it makes does the `DOCUMENT_TYPE_NODE` check before making the document.contains check, so it expects behavior different from what the specification currently requires.
