### ISSUE TITLE
Skip posting a task for `selectionchange` event in some cases

### ISSUE THREAD

**Issue by ShuangshuangZhou** [w3c/selection-api#170]
Hello!

We may consider to skip posting a task for the `selectionchange` event in some specific cases like:

- Skip posting a task for `selectionchange` event if there are no registered listeners;
- Skip posting a task for `selectionchange` event if the UA already has an queued task for an equivalent `selectionchange` event;

Here is a simple case when we don't have any registered listener:
```
<!DOCTYPE html>
<html>
<form>
    <div>
        <input
        class="toggle-all"
        type="text"
        id="inputtext"
        name="subscribe"
        value="hello world"/>
    </div>
  </form>

  <script>
  var tx = document.getElementById("inputtext");
  tx.focus();
  for (var i = 0; i < 100; i++) {

    console.time("set value");
    tx.value = 'something to do ' + i;
    console.timeEnd("set value");
  }
  </script>
  </html>
```

Based the below chrome trace, it is noticed that although we don't register any listener, it still posts an async task when we are just changing the text value.
![selectionchange-for-w3c](https://github.com/w3c/selection-api/assets/76035035/6b038f84-2432-4452-a68e-4c3ca4fc5bf1)

**Comment by tkent-google** [comment]
@rniwa What do you think about this optimization?  Chromium is positive about it.

It's a web-exposed change.  But I guess it won't cause compatibility issues.

**Comment by ShuangshuangZhou** [comment]
Hi@rniwa Sorry to disturb, any comments on this?
Besides in Chromium, I take a look in WebCore, seems that WebCore also enqueue events([link](https://github.com/WebKit/WebKit/blob/a18f3e115c5277f715d33631a60462e361bd2dc4/Source/WebCore/editing/FrameSelection.cpp#L435)) without checking whether the event has related listeners. Speedometer2.1/3 might get some progression when skipping these events w/o listeners.

Thanks!

**Comment by rniwa** [comment]
What is the script observable behavior difference?

**Comment by ShuangshuangZhou** [comment]
On web user side, it has no observable behavior difference because currently we haven't registered any listeners(in the listed script).

Skip enqueueing and dispatching this event without listeners might have some benefits on performance, since the browser doesn't need to dispatch events and excute related task and save some CPU cycles.

**Comment by rniwa** [comment]
If there is no script observable behavior difference, I don't think we need to say one way or another in the spec.

**Comment by tkent-google** [comment]
1. There are no event listeners for `selectionchange`
2. `input.selectionEnd = 42` Update selection, and post a task to dispatch `selectionchagne`
3. `addEventListener('selectionchange', callback)`
4. Enter the event loop
5. The task is executed, and the callback is called.

The callback won't be called if UAs skip to post the task.

----

1. `addEventListener('selectionchange', callback)`
2. `input.selectionEnd = 42` Update selection, and post a task to dispatch `selectionchagne`
3. `input.selectionEnd = 41` Update selection, and post another task to dispatch `selectionchagne`
4. Enter the event loop
5. The tasks are executed, and the callback is called **twice**.

The callback will be called only **once** if UAs skip to post the second task.

**Comment by rniwa** [comment]
I see. That sounds like something that could potentially pose a web compatibility problem to me. Also, generally speaking, we don't want to change the UA behavior based on whether an event listener is present or not. So that makes me think that we probably don't want to avoid posting a task even when there is no event listener but perhaps we can add a flag to check whether a task to fire `selectionchange` had already been scheduled or not.

**Comment by ShuangshuangZhou** [comment]
I see. Maybe the logic here is something like below(flag `selection_change_event_scheduled` is set to false by default)?
```
if (!document.selection_change_event_scheduled) {
  post_selection_change_task();
  document.selection_change_event_scheduled = true;
  ...
}
 
.....
 
selection_change_task_callback(){
  ...
  document.selection_change_event_scheduled = false;
}
```

**Comment by rniwa** [comment]
Well, you need to reset the flag at the beginning of the callback, not at the end, but yeah.

**Comment by ShuangshuangZhou** [comment]
Got it. Thx for the correction. So officially, we need to write this into the `selectionchange-event` [spec](https://www.w3.org/TR/selection-api/#selectionchange-event), right? What is the subsequent process like?

Thanks!

**Comment by annevk** [comment]
Yeah, a PR against this repository as well as a PR against web-platform-tests for test coverage. And ideally some indication that multiple implementers are on board.

**Comment by rniwa** [comment]
Hm... this issue interacts with https://github.com/w3c/selection-api/issues/53. The spec currently specifies Firefox's behavior of firing `selectionchange` event at `input` and `textarea` elements. However, this is problematic with respect to the new boolean state we're considering to introduce in this issue. It would be odd for the boolean state to be document-wide if we kept the current model since `selectionchange` maybe scheduled to be fired on different `input` elements. An obvious alternative is to have a boolean state per each `input` / `textarea` element. Either way, we need to figure out which behavior is most web compatible & makes most sense.

**Comment by ShuangshuangZhou** [comment]
Hi Rniwa, thanks for the sharing! I've read issue[#53](https://github.com/w3c/selection-api/issues/53) and basically understand what you guys want to do. You'd like to fire `selectionchange` event for each element(`input` or `textarea`) when it is changed no matter the element is focused or not, right?

I take a look on the definition of [`selection`](https://www.w3.org/TR/selection-api/#definition) in the spec, seems that one document only have one unique `selection`, so only the change on the focused element should fire the event, right? So why the spec keeps the same? Is there anything blocked what we want to do in issue[#53](https://github.com/w3c/selection-api/issues/53)?

Please corret me if my understanding is wrong. Thanks!

**Comment by rniwa** [comment]
So now we have [a PR for spec change](https://github.com/w3c/selection-api/pull/172) and [a PR for WPT](https://github.com/web-platform-tests/wpt/pull/45145).

**Comment by rniwa** [comment]
So my proposal as the editor of a spec is as follows. We introduce boolean state *has scheduled selectionchange event* on document, input element, and textarea element. We introduce two algorithms:
* **To schedule a `selectionchange` event** on a node *target* -  If the boolean state of *target* is false, this algorithm queues a task to *fire a `selectionchange` event* and sets the boolean state of *target* to true. Otherwise, if the boolean state of *target* is true, it does nothing.
* **To fire a `selectionchange` event** on a node *target* - Sets the boolean state of *target* to false and fires `selectionchange` event on *target*.
