### ISSUE TITLE
Why does getRangeAt must return a reference to (not a copy of) the range?

### ISSUE THREAD

**Issue by kojiishi** [w3c/selection-api#40]
The spec currently say:

> it must return a reference to (not a copy of) the context object's range.

and in its following note, it says it's currently not interoperable. Are there any reasons or good use cases to make this a "must" when implementations are not interoperable?

**Comment by rniwa** [comment]
I think the point of this spec. is agree on these API differences.  Since this behavior is observable by JavaScript and Web apps could rely on one behavior or other, it would be good to agree on one behavior.

https://bugzilla.mozilla.org/show_bug.cgi?id=671152 suggests that Mozilla is interested in changing their behavior to return a clone.

**Comment by rniwa** [comment]
Posted on public-webapps: http://lists.w3.org/Archives/Public/public-webapps/2015JanMar/0029.html

**Comment by rniwa** [comment]
Blink now aligns its behavior with Gecko. The only remaining engine to behave differently (i.e. returns a copy) is WebKit so we're not making any spec changes.
