### ISSUE TITLE
Clarify the additions of this spec to GlobalEventHandlers

### ISSUE THREAD

**Issue by ehsan** [w3c/selection-api#54]
It seems to me that this spec needs to include the following IDL changes for the event handlers that it adds, something like:

```
partial interface GlobalEventHandlers {
  attribute EventHandler onselectstart;
  attribute EventHandler onselectionchange;
};
```

**Comment by rniwa** [comment]
I think the consistency triumphs here. Will add it to the spec.

@foolip

**Comment by ehsan** [comment]
We should also add both of them to Element as well, since the events can be dispatched to elements too.

**Comment by foolip** [comment]
Blink has onselectionchange + onselectstart on Document and onselectstart on Element.

WebKit looks like the same but it also has onselectionchange on HTMLBodyElement, and all of the attributes have [NotEnumerable] which they don't in Blink.

Gecko has onselectionchange on Document and onselectstart already in GlobalEventHandlers it seems.

So, sounds like a plan, unless anyone has reason to suspect compat risk one way or another?

**Comment by foolip** [comment]
Did a bit of testing in Edge, and it looks like they have onselectionchange + onselectstart on Document and onselectstart on **HTMLElement**.

Do any of these events ever bubble to window, or would it make sense to just spec what Blink+Edge+WebKit have?

@ojanvafai from editing/OWNERS in Blink.

**Comment by rniwa** [comment]
I'm pretty certain `document.body.onselectstart` needs to work because of the way the design mode treats the body as the editing host.  So for consistency, it's probably a good idea to have `onselectionchange` work there as well.

That makes me think that adding both `onselectionchange` and `onselectstart` on `Element` and `Document` is the right approach here.

**Comment by foolip** [comment]
I tried http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4379 and it looks like the selectstart event bubbles to window everywhere, so putting at least onselectstart on GlobalEventHandlers would make sense. (Note that it's HTMLElement and SVGElement that implement GlobalEventHandlers, not Element, but that's probably a safe change given Edge's behavior.)

As for onselectionchange, it looks like the event target is always the document, and it doesn't bubble? The odd thing is that AFAICT it's the only onfoo attribute on body that forwards to the document instead of the window. Blink supports on the content attribute here, not the IDL attribute like WebKit. I could add a use counter for that, maybe try spec'ing it only on Document and revisit if it looks like usage isn't zero?

**Comment by rniwa** [comment]
Getting the usage statistics would be useful.

**Comment by foolip** [comment]
Submitted https://codereview.chromium.org/2249613002/ for review.

How about starting with `onselectionchange` on Document only for now and adding it to HTMLBodyElement later to match Blink+WebKit if removal seems too risky?

**Comment by rniwa** [comment]
Well, if we're adding it to `Element` as originally proposed, then the only thing we have to worry about is where we're firing the event at.  Do we have any data on that?

**Comment by foolip** [comment]
Per my testing in https://github.com/w3c/selection-api/issues/54#issuecomment-239574361 the selectionchange event fires on document and doesn't bubble. In both Blink and WebKit, it's only fired at a single place in FrameSelection.cpp.

I tried to grep gecko-dev but am not sure I'm reading it right. @ehsan, does Gecko ever fire selectionchange elsewhere, or is there a spec discussion about making it so that's the background for this issue?

**Comment by rniwa** [comment]
Added a tentative spec text in https://github.com/w3c/selection-api/commit/64802693414d842d1c0273f9fee019602710fe8c.  Please file a new issue if your finding requires a spec change.

**Comment by foolip** [comment]
Thanks, followed up in https://github.com/w3c/selection-api/issues/75

**Comment by ehsan** [comment]
> I tried to grep gecko-dev but am not sure I'm reading it right. @ehsan, does Gecko ever fire selectionchange elsewhere

We also only currently dispatch this event to Document in non-bubbling mode.

**Comment by foolip** [comment]
The use counter from https://github.com/w3c/selection-api/issues/54#issuecomment-239787546 is in Chrome 54 which just reached stable:
https://www.chromestatus.com/metrics/feature/timeline/popularity/1508

That's still rolling out, but internal data suggests usage around 0.0000001% in chromestatus.com terms. So given the lack of interop there, I think removing it ought to work out. @rniwa, WDYT?
